### ISSUE TITLE
WindowLeaked crash 

### ISSUE THREAD

**Issue by sharon-pl** [lovecoding530/SafetyApp-chat#40]
Thu Mar 21 00:00:00 EDT 2019
Mon May 12 00:00:00 EST 10
===================================
MainActivity onResume
monthSpinner.setOnItemSelectedListener: 9
android.view.WindowLeaked: Activity com.coretal.carinspection.activities.MainActivity has leaked window DecorView@2368326[MainActivity] that was originally added here
at android.view.ViewRootImpl.<init>(ViewRootImpl.java:621)
at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:383)
at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:95)
at android.app.Dialog.show(Dialog.java:342)
at com.coretal.carinspection.dialogs.API_PhoneNumberDialog$1.onClick(API_PhoneNumberDialog.java:92)
at android.view.View.performClick(View.java:7161)
at android.view.View.performClickInternal(View.java:7133)
at android.view.View.access$3500(View.java:804)
at android.view.View$PerformClick.run(View.java:27416)
at android.os.Handler.handleCallback(Handler.java:883)
at android.os.Handler.dispatchMessage(Handler.java:100)
at android.os.Looper.loop(Looper.java:241)
at android.app.ActivityThread.main(ActivityThread.java:7604)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:941)
android.view.WindowLeaked: Activity com.coretal.carinspection.activities.MainActivity has leaked window DecorView@3bd8a5d[MainActivity] that was originally added here
at android.view.ViewRootImpl.<init>(ViewRootImpl.java:621)
at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:383)
at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:95)
at android.app.Dialog.show(Dialog.java:342)
at androidx.fragment.app.DialogFragment.onStart(DialogFragment.java:458)
at androidx.fragment.app.Fragment.performStart(Fragment.java:2568)
at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:921)
at androidx.fragment.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManagerImpl.java:1233)
at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:1299)
at androidx.fragment.app.BackStackRecord.executeOps(BackStackRecord.java:688)
at androidx.fragment.app.FragmentManagerImpl.executeOps(FragmentManagerImpl.java:2069)
at androidx.fragment.app.FragmentManagerImpl.executeOpsTogether(FragmentManagerImpl.java:1859)
at androidx.fragment.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManagerImpl.java:1814)
at androidx.fragment.app.FragmentManagerImpl.execPendingActions(FragmentManagerImpl.java:1721)
at androidx.fragment.app.FragmentManagerImpl.dispatchStateChange(FragmentManagerImpl.java:2623)
at androidx.fragment.app.FragmentManagerImpl.dispatchPause(FragmentManagerImpl.java:2595)
at androidx.fragment.app.FragmentController.dispatchPause(FragmentController.java:280)
at androidx.fragment.app.FragmentActivity.onPause(FragmentActivity.java:407)
at com.coretal.carinspection.activities.MainActivity.onPause(MainActivity.java:218)
at android.app.Activity.performPause(Activity.java:7998)
at android.app.Instrumentation.callActivityOnPause(Instrumentation.java:1529)
at android.app.ActivityThread.performPauseActivityIfNeeded(ActivityThread.java:4711)
at android.app.ActivityThread.performPauseActivity(ActivityThread.java:4672)
at android.app.ActivityThread.handlePauseActivity(ActivityThread.java:4624)
at android.app.servertransaction.PauseActivityItem.execute(PauseActivityItem.java:46)
at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2183)
at android.os.Handler.dispatchMessage(Handler.java:107)
at android.os.Looper.loop(Looper.java:241)
at android.app.ActivityThread.main(ActivityThread.java:7604)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:941)
Start vehicle number: 66022301
[1466] BasicNetwork.performRequest: Unexpected response code 500 for http://192.168.0.122:8080/Peled_v6/restful/vehicle/getVehicleData/6783279218/66022301
getting logs
getting logs

**Comment by kpstar** [comment]
done
