### ISSUE TITLE
FATAL EXCEPTION: IndexOutOfBoundsException

### ISSUE THREAD

**Issue by sharon-pl** [lovecoding530/SafetyApp-chat#41]
FATAL EXCEPTION: main
Process: com.coretal.carinspection, PID: 30687
java.lang.IndexOutOfBoundsException: Index: 3, Size: 3
at java.util.ArrayList.remove(ArrayList.java:503)
at com.coretal.carinspection.fragments.DateAndPictureFragment$1$1.onClick(DateAndPictureFragment.java:123)
at com.android.internal.app.AlertController$ButtonHandler.handleMessage(AlertController.java:177)
at android.os.Handler.dispatchMessage(Handler.java:107)
at android.os.Looper.loop(Looper.java:241)
at android.app.ActivityThread.main(ActivityThread.java:7604)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:941)
10-02 19:08:47.538 31145 31145 E l.carinspectio: Unknown bits set in runtime_flags: 0x8000

**Comment by kpstar** [comment]
done
